In [1]:
from shapely.geometry import Point
import pandas as pd
import geopandas as gpd
import pandas as pd

In [2]:
import requests
import geojson
import json

In [3]:
with open('../data/WeGo.json') as fi:
    credentials = json.load(fi)

In [4]:
Authorization = credentials['Authorization']

In [30]:
URL = 'https://api.goswift.ly/speed-map/nashville/route/22'



params_JanFeb_TustoThru = {
    'direction': '1', 
    'startDate': '01-25-2022',
    'endDate': '02-24-2022',
    'daysOfWeek': '2,3,4',
    'beginTime':'06:00',
    'endTime': '09:00',
    'resolution': 'hiRes',
}

params_geo_JanFeb_TustoThru  = {
    'direction': '1',
    'startDate': '01-25-2022',
    'endDate' : '02-24-2022',
    'format'   : 'geojson',
    'daysOfWeek': '2,3,4',
    'beginTime' : '06:00',
    'endTime' : '09:00',
    'resolution': 'hiRes'
}

headers = {'Authorization': Authorization,
          'Content-Type': 'application/json'}

In [31]:
response_geo11 = requests.get(URL, params = params_geo_JanFeb_TustoThru, headers = headers)
result_geo11 =response_geo11.json()['features']
georout22_Tu_thu_gdf=gpd.GeoDataFrame.from_features(result_geo11)
georout22_Tu_thu_gdf.head(3)

,geometry,fromStopId,fromStopName,toStopId,toStopName,pathLengthMeters,averageTravelSeconds,averageTravelSpeed,maxSecs,percent90Secs,percent80Secs,percent70Secs,medianSecs,percent30Secs,percent10Secs,minSecs
0,"LINESTRING (-86.83661 36.19440, -86.83684 36.1...",HAMHYDWN,S Hamilton Rd & N Hydes Ferry Rd Wb,JOHASHWF,John Mallette Dr & Ashton Ave Wb,24.046,13.270667,1.811966,23.794,21.994,19.667,16.882,14.6090,7.537,4.910,4.261
1,"LINESTRING (-86.83752 36.18973, -86.83770 36.1...",COUDOAWN,County Hospital Rd & Doak Ave Wb,COUHYDWF,County Hospital Rd & Hydes Ferry Rd,24.241,1.736833,13.957013,4.951,1.933,1.752,1.700,1.5445,1.447,1.294,1.103
2,"LINESTRING (-86.81430 36.18268, -86.81428 36.1...",23ASEINF,23rd Ave N & Seifried St Nb,23ACLANN,23rd Ave N & Clarksville Pike Nb,22.407,2.315978,9.674962,7.796,2.923,2.511,2.349,2.1360,1.874,1.657,1.080

In [32]:
response_geo22 = requests.get(URL, params = params_JanFeb_TustoThru , headers = headers)
result22 =response_geo22.json()
rout22b_tus_thu_df=pd.DataFrame(result22['data']['segments'])
rout22b_tus_thu_df.head(3)

,pathLocs,maxSecs,percent90Secs,percent80Secs,percent70Secs,medianSecs,percent30Secs,percent20Secs,percent10Secs,minSecs,pathLengthMeters,averageTravelSeconds,averageTravelSpeed,toStop,fromStop,countForSegment
0,"[{'lat': 36.194401139132985, 'lon': -86.836605...",23.794,21.994,19.667,16.882,14.6090,7.537,6.079,4.910,4.261,24.046,13.270667,1.811966,"{'configRev': 49, 'stopPathId': 'HAMHYDWN_to_J...","{'configRev': 49, 'stopPathId': 'CLAMETSN_to_H...",15
1,"[{'lat': 36.18972789789641, 'lon': -86.8375232...",4.951,1.933,1.752,1.700,1.5445,1.447,1.331,1.294,1.103,24.241,1.736833,13.957013,"{'configRev': 49, 'stopPathId': 'COUDOAWN_to_C...","{'configRev': 49, 'stopPathId': 'HAMHYDWN_to_C...",30
2,"[{'lat': 36.18268124690563, 'lon': -86.8143031...",7.796,2.923,2.511,2.349,2.1360,1.874,1.757,1.657,1.080,22.407,2.315978,9.674962,"{'configRev': 49, 'stopPathId': '23ASEINF_to_2...","{'configRev': 49, 'stopPathId': 'BUC23AWN_to_2...",134

In [28]:
rout22_inbound_concat2 = pd.concat([georout22_Tu_thu_gdf,rout22b_tus_thu_df[['countForSegment','percent20Secs']]], axis = 1)
rout22_inbound_concat2.head(3)

,geometry,fromStopId,fromStopName,toStopId,toStopName,pathLengthMeters,averageTravelSeconds,averageTravelSpeed,maxSecs,percent90Secs,percent80Secs,percent70Secs,medianSecs,percent30Secs,percent10Secs,minSecs,countForSegment,percent20Secs
0,"LINESTRING (-86.83661 36.19440, -86.83684 36.1...",HAMHYDWN,S Hamilton Rd & N Hydes Ferry Rd Wb,JOHASHWF,John Mallette Dr & Ashton Ave Wb,24.046,13.270667,1.811966,23.794,21.994,19.667,16.882,14.6090,7.537,4.910,4.261,15,6.079
1,"LINESTRING (-86.83752 36.18973, -86.83770 36.1...",COUDOAWN,County Hospital Rd & Doak Ave Wb,COUHYDWF,County Hospital Rd & Hydes Ferry Rd,24.241,1.736833,13.957013,4.951,1.933,1.752,1.700,1.5445,1.447,1.294,1.103,30,1.331
2,"LINESTRING (-86.81430 36.18268, -86.81428 36.1...",23ASEINF,23rd Ave N & Seifried St Nb,23ACLANN,23rd Ave N & Clarksville Pike Nb,22.407,2.315978,9.674962,7.796,2.923,2.511,2.349,2.1360,1.874,1.657,1.080,134,1.757