In [1]:
pip install sodapy

Requirement already satisfied: sodapy in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (2.1.1)
Requirement already satisfied: requests>=2.20.0 in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (from sodapy) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (from requests>=2.20.0->sodapy) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (from requests>=2.20.0->sodapy) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (from requests>=2.20.0->sodapy) (2.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\vital\anaconda3\envs\geospatial\lib\site-packages (from requests>=2.20.0->sodapy) (1.26.9)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from sodapy import Socrata

In [11]:
from shapely.geometry import Point
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster
from folium.plugins import FastMarkerCluster

In [12]:
client = Socrata("data.nashville.gov", None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [13]:
results = client.get("vfe9-k7vc", limit=5000)

In [14]:
results_df = pd.DataFrame.from_records(results)
results_df

,stop_id_number,stop_abbreviation,stopname,shelter,bench,route_name,route_number,geocoded_column,:@computed_region_p6sk_2acq,:@computed_region_gxvr_9jxz,:@computed_region_wvby_4s8j,:@computed_region_3aw5_2wv7,:@computed_region_sjpq_96s8,:@computed_region_f73m_vb2k,:@computed_region_c9xn_skx3,:@computed_region_gisn_y5cm,:@computed_region_v3ji_vzam,:@computed_region_cfa7_hbpz
0,5120,7AVUNINN,7TH AVE & UNION ST NB,False,False,AIRPORT - DOWNTOWN HOTELS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5455,CM5_4,Temporary Bay 4,False,False,HERMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2762,23ACLASF,23RD AVE N & CLARKSVILLE PIKE SB,False,False,BORDEAUX,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4079,21ACHUSN,21ST AVE N & CHURCH ST SB,False,True,MIDTOWN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4133,GRWHIWN,GREEN LN & WHITES CREEK PIKE WB,False,False,GOLDEN VALLEY,41,"{'latitude': '36.236249', 'longitude': '-86.81...",16,6,1,1,30386,1,9,6,2005,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2573,5166,JEF6AVWM,JEFFERSON ST & 6TH AVE WB,False,False,MUSIC CITY BLUE CIRCUIT,60,"{'latitude': '36.173796', 'longitude': '-86.78...",20,51,1,1,NaN,1,13,6,2005,NaN
2574,4698,NEEJAPEF,NEELY'S BEND RD & JASPERSON DR EB,False,False,MADISON CONNECTOR,76,"{'latitude': '36.247943', 'longitude': '-86.68...",4,12,1,2,1527,2,4,4,2005,NaN
2575,4700,NEEALLEN,NEELY'S BEND RD & ALLEN PASS EB,False,False,MADISON CONNECTOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2576,4714,OLDFORWN,OLD HICKORY BLVD & FOREST PARK RD WB,False,False,MADISON CONNECTOR,76,"{'latitude': '36.263003', 'longitude': '-86.70...",4,12,1,1,1527,2,4,4,2005,NaN
2577,1940,THOEIREF,THOMPSON LN & EAST IRIS DR,False,False,THOMPSON CONNECTOR,77,"{'latitude': '36.111799', 'longitude': '-86.76...",9,25,1,1,30813,9,21,5,2005,NaN

In [16]:
results_df.plot()

TypeError: no numeric data to plot